#!/bin/bash

rm /dnnwebportal/src/app/resource/sshweb.json

echo {"\"host\"":\"$1\", "\"port\"":\"$2\"} > /dnnwebportal/src/app/resource/sshweb.json

cat /dnnwebportal/src/app/resource/sshweb.json

cd /dnnwebportal

npm run app

rm -r /usr/share/nginx/html/DNN

cp -r build/ /usr/share/nginx/html/DNN