#!/bin/bash

cp Dockerfile ../../../
cp -r nginx ../../../nginx
cd ../../../

if [ -z "$1" ];
  then
    docker build -t dnn-web-gui:dev .
else
    docker build -t dnn-web-gui:$1 .

rm -r nginx/
rm Dockerfile
